<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.25">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.25" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\Catalog\" />
    <Folder Include="Controllers\Reference\" />
    <Folder Include="Controllers\Product\" />
    <Folder Include="Repositories\Projects\" />
    <Folder Include="Services\Catalog\Interfaces\" />
    <Folder Include="Services\Product\Interfaces\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Models\DTOS\Access\AppUserRoleDto.cs" />
  </ItemGroup>

</Project>
